spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aohuanhuan/SpringCloudLearning.git
          search-paths: SpringCloud-Config
          basedir: E:\Program\SprintBoot\SpringCloudLearning
          clone-on-start: true
server:
  port: 8811
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/