server:
  port: 8888
eureka:
  instance:
    #指注册中心在接收到最后一个心跳之后等待的时间（秒），然后才能从此视图中删除此实例，并禁止此实例的流量
    lease-expiration-duration-in-seconds: 15
    #指注册的客户端服务需要向注册中心发送心跳以指示它仍然存在的频率（以秒为单位）。如果在leaseExpirationDurationInSeconds中指定的时间段内未收到心跳线，则eureka服务器将从其视图中删除该实例，因此不允许此实例的流量
    lease-renewal-interval-in-seconds: 10
    #用来开启是否使用ip识别服务 当该变量为 true 时 此时 将会使用您的 内网ip去注册服务, 当您的服务注册中心是基于内网的服务,那么 配置服务到这一步即可.
    prefer-ip-address: true
  client:
    #当为单注册中心时, 做为注册中心,本服务当然不能注册自己，下面两项配置为 false 服务才可以正常启动,当为多注册中心时不配置,但是defaultZone必须配置为非己 的url地址
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/